select distinct
    CLASS_PROJECT.YT_TRENDING_DATA.DIM_VIDEO_SEQ.NEXTVAL AS VIDEO_KEY,
    VIDEO_ID,
    TITLE,
    DESCRIPTION,
    PUBLISHEDAT,
    TRENDING_DATE,
    VIEW_COUNT,
    LIKES,
    DISLIKES,
    COMMENT_COUNT,
    TAGS,
    THUMBNAIL_LINK,
    COMMENTS_DISABLED,
    RATINGS_DISABLED,
    CURRENT_TIMESTAMP() AS DW_CREATE_TS, 
    CURRENT_TIMESTAMP() AS DW_UPDATE_TS
from CLASS_PROJECT.YT_TRENDING_DATA.STG_US_YT_TRENDING
qualify row_number() over (partition by VIDEO_ID order by VIEW_COUNT desc) = 1