select distinct
    ID AS CATEGORYID, 
    TITLE, 
    ASSIGNABLE, 
    CURRENT_TIMESTAMP() AS DW_CREATE_TS, 
    CURRENT_TIMESTAMP() AS DW_UPDATE_TS
from CLASS_PROJECT.YT_TRENDING_DATA.STG_US_YT_CATEGORY