SELECT
    VIDEO_ID,
    CHANNELID,
    CATEGORYID,
    CURRENT_TIMESTAMP() AS DW_CREATE_TS, 
    CURRENT_TIMESTAMP() AS DW_UPDATE_TS
FROM CLASS_PROJECT.YT_TRENDING_DATA.STG_US_YT_TRENDING
qualify row_number() over (partition by VIDEO_ID order by VIEW_COUNT desc) = 1