SELECT 
    A.*, 
    B.TITLE AS CATEGORY 
FROM CLASS_PROJECT.YT_TRENDING_DATA.STG_US_YT_TRENDING A
LEFT JOIN CLASS_PROJECT.YT_TRENDING_DATA.STG_US_YT_CATEGORY B
ON A.CATEGORYID = B.ID
ORDER BY A.TRENDING_DATE DESC