name: 'fiu_dbt'
version: '1.0.0'

profile: 'fiu_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fiu_dbt:
    yt_trending_data:
      dim_video:
        +materialized: incremental
        +unique_key: video_id
        +incremental_strategy: merge
        +merge_exclude_columns: ["DW_CREATE_TS", "VIDEO_KEY"]
      dim_channel:
        +materialized: incremental
        +unique_key: channelid
        +incremental_strategy: merge
        +merge_exclude_columns: ["DW_CREATE_TS", "CHANNEL_KEY"]
      dim_category:
        +materialized: incremental
        +unique_key: categoryid
        +incremental_strategy: merge
        +merge_exclude_columns: ["DW_CREATE_TS", "CATEGORY_KEY"]
      fact_yt_trending:
        +materialized: incremental
        +unique_key: ['VIDEO_KEY', 'CHANNEL_KEY', 'CATEGORY_KEY']
        +incremental_strategy: merge
        +merge_exclude_columns: ["DW_CREATE_TS"]